### ISSUE TITLE
Tlauncher (not premium users) crash on join. 

### ISSUE THREAD

**Issue by dorianxonic** [montlikadani/TabList#101]
### Describe your problem to what is
```
Plugin causes clients to crash when their client is not the Mojang provided one.
```

### Details
Plugin version: 
```
Paper 176.
```

### Console error
```
> [07:26:56] [Client thread/FATAL]: Error executing task on Client
> java.lang.NullPointerException: null
> 	at dkc.a(SourceFile:1976) ~[1.14.4.jar:?]
> 	at nb.a(SourceFile:122) ~[1.14.4.jar:?]
> 	at nb.a(SourceFile:16) ~[1.14.4.jar:?]
> 	at ke.a(SourceFile:21) ~[1.14.4.jar:?]
> 	at agq.h(SourceFile:144) [1.14.4.jar:?]
> 	at agu.h(SourceFile:23) [1.14.4.jar:?]
> 	at agq.q(SourceFile:118) [1.14.4.jar:?]
> 	at agq.bh(SourceFile:103) [1.14.4.jar:?]
> 	at cyc.e(SourceFile:915) [1.14.4.jar:?]
> 	at cyc.b(SourceFile:410) [1.14.4.jar:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:155) [1.14.4.jar:?]
Here I am!
```

### Configuration file(s)
Send the configuration file(s).
[config.yml](https://pastebin.com/MHuWHfip)

### Screenshots (optional)
Send a few pictures about the problem if you can.

**Comment by montlikadani** [comment]
The console error is not mine. This is just a memory error for the client, restart and should work.

**Comment by dorianxonic** [comment]
Restarting, re-installing both java/client do not work alltogether. I went from plugin to plugin to see which one causes the issue. That's the only error I could see. A different plug-in with similar capabilities does not cause the issue, but it doesn't look as nice as this one.

**Comment by dorianxonic** [comment]
If it is helpful: occasionally client did not crash on my test sessions, but it crashed again whenever a new world was entered (nether, overworld).

**Comment by montlikadani** [comment]
Well, TLauncher as you could see is no longer in development, but still functional. I use it too, but not for long to avoid errors. The first source of the error may be an older client or an underdeveloped client that does not provide a fix. The second may be a relationship with two parties that has not been tested. This bug has never occurred to me since I was developing this plugin. The bug that I need to fix is sent by a server that contains the source of the bug for my code. So first, check the server console and send it here. What console error you need to find: find with "tablist" name.

**Comment by montlikadani** [comment]
Re-installing client will fix it.
