### ISSUE TITLE
How to use another vanish plugin?

### ISSUE THREAD

**Issue by Quenteez** [montlikadani/TabList#110]
I use VanishNoPacket plugin with myself update to higher version than it exist now on Bukkit, but TabList not support it ;( It is a big pity for me. Ok, your plugin hide vanished players in tab with VNP, but not in placeholder %online-players%. What can I do? Please, help!

**Comment by montlikadani** [comment]
VanishNoPacket is not updated since 2018. The plugin API too poor. Otherwise, old and non-upgraded plugins are not willing to be supported as they may cause errors.

**Comment by Quenteez** [comment]
I can send you VNP for 1.12.2, exist a chance that you will add it to plugin support?
If I have a sources of TabList, I will add it myself, but without sources I can't.

**Comment by montlikadani** [comment]
> I can send you VNP for 1.12.2, exist a chance that you will add it to plugin support?

Well, as long as there is no official update or developer API, we are not willing to integrate the vanish plugin into the tablist. If the developer makes any changes, either after the upgrade or by retrieving the source, it will be integrated with it.
> If I have a sources of TabList, I will add it myself, but without sources I can't.

The plugin is not open source, due to curious and stolen people.

I recommend talking to the developer when an official release is expected.

**Comment by Quenteez** [comment]
I think the developer will not release a new version, XD

**Comment by montlikadani** [comment]
VanishNoPacket seems to be not developer anymore since 2018. I recommend you to use at least SuperVanish or PremiumVanish which is supported.
