### ISSUE TITLE
Everyone with the same prefix as someone thats AFK shows as AFK

### ISSUE THREAD

**Issue by Seamonster778778778788** [montlikadani/TabList#133]
### Problem

When one person with a prefix goes afk, everyone else with that prefix shows as AFK in tab.
Sometimes, it flashes all with the same prefix as afk for a split second instead of staying solid afk for all of the prefix

### Details
Plugin version: 5.3.1

Software version: 
spigot
Relevant plugins: 
essentials, probably
### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

config.yml: 

https://pastebin.com/KEaXqyyQ
### Screenshots (optional)

![image](https://user-images.githubusercontent.com/34897864/80242203-984aaa80-862a-11ea-95b7-036ce95eba3a.png)

**Comment by CreepyCre** [comment]
I believe I am experiencing the same issue. (Not exactly the same, but the cause is likely the same)

On our server we have the groups.yml set up via permission nodes (every player has the tablist.default perm, which corresponds to the prefix/ suffix setting). Since a few hours ago all placeholders in groups.yml get resolved as if the player they were resolved for was the last player that joined. As with the issue above you can sometimes see the correct prefix/ suffix flashing through.

I also tried having the last player that joined do /afk and the afk tag was applied to all players.

**Comment by montlikadani** [comment]
Is this still reproduce in the latest version (v5.4.0)?
