### ISSUE TITLE
Your Plugin Just Crashed my Server 

### ISSUE THREAD

**Issue by Mobmaker55** [montlikadani/TabList#208]
### Problem
Hey! Your plugin here kinda crashed my server when I went /tablist reload
it was working two days ago, did you try to do some kind of over-the-air update that screwed over my server?
also if you just say "update to latest" I will ditch your plugin.

### Details
Plugin version: 5.5.1 (I know it's not latest)

Software version: 

Relevant plugins: 

### Console error
```
Insert here the console error if you have it.
```

### Configuration file(s)

configuration file:

**Comment by montlikadani** [comment]
> also if you just say "update to latest" I will ditch your plugin.

Oh, then remove your server, if you mean "dirty plugin"

**Comment by Mobmaker55** [comment]
> > also if you just say "update to latest" I will ditch your plugin.
> 
> Oh, then remove your server, if you mean "dirty plugin"

That doesn't even make sense. Also, you shouldn't literally cause every server running an older version of your plugin to break just because you have a new version out. If you have an auto-update ability, then that's fine! Auto-update AFTER my server restarts, don't crash it.

But don't go breaking Minecraft servers and being like "haha, update to latest." That's terrible code, and your updates really don't have that much of a reason to require a complete reinstall of the plugin every time you decide to patch issues.

**Comment by montlikadani** [comment]
I'm not going to make drama about this, but lot of popular plugins don't have auto-update feature implemented in their plugins code, as its only 2 clicks of plugin reinstalling after server stop. Yes, there are plugins which doing this, but half of it, is premium released. Otherwise, most plugins only perform a version check to notify the owner of fixes and new features. Simply if the server owner is just lazy, why he/she decided to make a server without updating the installed plugins if there is a new release? How did you updates your server or your system actually? This is not part of this, but in Linux, as far as I know, there is no automatic update to automatically update downloaded and installed packages when a new release is available. Have you ever seen an automatic update for a resource, even while the server is running? I haven't seen or heard from anyone... Otherwise, even if this automatic update were performed while the server was running, a server memory leak could occur because a plugin could not delete conditions from memory that store in other resources or server implementations.

I, at least, have a new update check implementation in this plugin that downloads the plugin's latest version into the releases directory so that once you see what it contains, you simply have to replace the old one with the downloaded one.

> That's terrible code, and your updates really don't have that much of a reason to require a complete reinstall of the plugin every time you decide to patch issues.

If you’re so eager for auto-updates, why not create a library and share it on Spigot Forums for developers to use?

Anyway, this plugin is not a premium to perform automatic updates.

Further: don’t spend this time with developers and others as to why there is no automatic update in this or any other resource, there is no point in arguing about this. Once implemented, it will be added.
