### ISSUE TITLE
Spigot/Paper 1.17 support

### ISSUE THREAD

**Issue by PLASTAR-2748** [montlikadani/TabList#246]
Tablist is doesnt work to new Spigot 1.17 please update this plugin

**Comment by TheNety** [comment]
Hi, support for Spigot/Paper 1.17 is planned. Currently we're waiting for Paper. Please wait patiently :)

**Comment by SlimeDog** [comment]
There is no ETA for Paper. Meanwhile, TabList doesn't work on Spigot 1.17. Any changes made for Spigot are guaranteed (by the Paper team) to work on Paper (Paper-specific optimizations will not work on Spigot, of course). Please update.

**Comment by montlikadani** [comment]
We're using Paper's new implementation called Adventure. Some of the tablist feature was deprecated and made it almost incompatible with the old ones. Most of these are improved, but I prefer to use the non-deprecated ones where possible.

**Comment by SlimeDog** [comment]
How do you use Adventure on the SpigotMC version of the plugin?

**Comment by montlikadani** [comment]
In answer to the question, the Paper repository is used by the TabList so I can access it.

When a plugin enters the loading process, it can check which server software is using either Paper or Spigot. This can be used to finalize a logical value into memory so that it can be used later or with any type of variable. I could also call this a multifunction implementation which can basically run on similar software with similar code with minor changes.

**Comment by SlimeDog** [comment]
Thanks for the details.

**Comment by SlimeDog** [comment]
As you no doubt know, there is some paper out there. We're testing paper 1.17-5 at present.  :)

**Comment by montlikadani** [comment]
The newest build in [Actions](https://github.com/montlikadani/TabList/actions) page now supports it.

**Comment by SlimeDog** [comment]
Nice. Looking good, in our admittedly limited usage. We employ prefixes and PAPI placeholders, but not some other features.

**Comment by montlikadani** [comment]
Official release is out on main sites.

**Comment by SlimeDog** [comment]
Indeed. Thanks.
